# Generated by Django 2.1 on 2018-09-16 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ca',
        ),
    ]
