# Generated by Django 2.1 on 2018-09-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_ca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('team_leader', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=10)),
                ('team_size', models.PositiveIntegerField()),
                ('accomodation', models.PositiveIntegerField(default=0)),
                ('offline_reg', models.BooleanField(default=False)),
                ('amount_paid', models.FloatField(default=0.0)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_id', models.CharField(max_length=50, null=True)),
                ('payment_request_id', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ('team_name',),
            },
        ),
    ]
