# Generated by Django 2.1 on 2018-09-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='e_against_all_odds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='e_cover_art',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='e_documentary_making',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='e_escapade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='e_write_o_maniac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='w_design',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='w_nikon',
            field=models.IntegerField(default=0),
        ),
    ]
