# Generated by Django 2.1 on 2018-09-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180919_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='w_design',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='w_nikon',
        ),
    ]
